services:
  - type: web
    name: age2meet-api
    runtime: python3
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: age2meet-db
          property: connectionString
    autoDeploy: true

databases:
  - name: age2meet-db
    databaseName: age2meet
    user: age2meet 