services:
  - type: web
    name: age2meet-api
    runtime: python3
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: age2meet-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: age2meet-db
    databaseName: age2meet
    user: age2meet 