# Generated by Django 5.2.3 on 2025-06-29 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('cuisine', 'Atelier Cuisine'), ('balade', 'Balade Nature'), ('musee', 'Visite Musée'), ('lecture', 'Club Lecture'), ('jardinage', 'Jardinage'), ('sport', 'Sport Doux'), ('art', 'Atelier Art'), ('jeux', 'Jeux de Société'), ('cinema', 'Cinéma'), ('theatre', 'Théâtre'), ('danse', 'Danse'), ('cafe', 'Café Rencontre'), ('autre', 'Autre')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='facile', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activity_images/')),
                ('requirements', models.TextField(blank=True, help_text='Matériel nécessaire, prérequis, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('message', 'Nouveau message'), ('contact_request', "Demande d'ami"), ('contact_accepted', 'Ami accepté'), ('activity_reminder', 'Rappel activité'), ('activity_cancelled', 'Activité annulée'), ('activity_updated', 'Activité modifiée'), ('event_reminder', 'Rappel événement'), ('system', 'Notification système'), ('welcome', 'Bienvenue')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, help_text='URL pour action liée à la notification', max_length=500)),
                ('related_object_id', models.IntegerField(blank=True, help_text="ID de l'objet lié (message, activité, etc.)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_participated', models.IntegerField(default=0)),
                ('events_created', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('friends_count', models.IntegerField(default=0)),
                ('profile_views', models.IntegerField(default=0)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('no_show', 'Absent')], default='confirmed', max_length=10)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes personnelles ou besoins spéciaux')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback', models.TextField(blank=True, help_text="Commentaire après l'activité")),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='backend.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_date'],
                'unique_together': {('user', 'activity')},
            },
        ),
    ]
